<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{75da618d-82b5-4924-8926-19f065104ee3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bEnable : BOOL;
	bStart : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[bEnable:=bStart;
P_task1();
p_task2();
p_task3();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>